version: '3'

services:
    mongodb:
      image: mongo:8.0.0
      restart: always
      ports: 
        - 27027:27017
      environment:
        MONGO_INITDB_ROOT_USERNAME: silla_like
        MONGO_INITDB_ROOT_PASSWORD: silla_like
        # MONGO_INITDB_DATABASE: silla_Like
      volumes:
        - silladata:/data/db

volumes:
  silladata: