services:
  app:
    container_name: silla_link_production
    build:
      context: .
      target: production
    ports:
      - "5000:5000"
    env_file:
      - ./production.env
    restart: always
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app-network
